config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#index'

  resources :posts
  resources :comments
  resources :users
  get 'user', to: 'users#show_current_user'
  post 'post_votes/:id', to: 'post_votes#create'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :content, :presence => true, :length => {maximum: 140}

end

app/models/post.rb
class Post < ActiveRecord::Base
  
  belongs_to :user

  has_many :comments
  has_many :post_votes

  URL_REGEX = /https?:\/\/[\S]+/

  validates :title, :length => {maximum: 140 }, :presence => true
  validates :url, :length => {maximum: 2083}, :allow_blank => true, :format => { with: URL_REGEX}

  validate :spam_free

  validate :onlytwenty

  private
  def spam_free
    last_post = Post.order(:created_at).last
    # latest_time = last_post.created_at

    if Post.any? and last_post.created_at > 1.minute.ago
      self.errors.add(:base, "Cannot post within 1 minute")
    end
  end

  def onlytwenty
    post_count = Post.count
    if post_count > 200
      self.errors.add(:base, "Cannot post more than 20 entries")
    end
  end
end

app/models/post_vote.rb
class PostVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
  has_many :post_votes

  has_attached_file :avatar,
                    :storage => :s3,
                    :s3_credentials => Proc.new{ |a| a.instance.s3_credentials },
                    :styles => { :medium => "300x300>", :thumb => "100x100" }, 
                    :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  def s3_credentials
    {:bucket => ENV['S3_BUCKET'], :access_key_id => ENV['ACCESS_KEY_ID'], :secret_access_key => ENV['SECRET_ACCESS_KEY']}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  protect_from_forgery

  after_filter :set_csrf_cookie_for_ng

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

protected

  # In Rails 4.2 and above
  # def verified_request?
  #   super || valid_authenticity_token?(session, request.headers['X-XSRF-TOKEN'])
  # end

  # In Rails 4.1 and below
  def verified_request?
    super || form_authenticity_token == request.headers['X-XSRF-TOKEN']
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    # params([:comment][:content]) ---> dog
    # params([:comment][:post_id]) ---> 3
    # binding.pry
    @myComment = current_user.comments.new(comment_params)
    if @myComment.save
      # tells computer that it needs to render pages in the following format
      respond_to do |format|
        #order matters here. its going to show javascript (json) response first

        #in Rails, the convention is we need to create a 'create.js.erb' file inside comments view folder
        format.js {render 'create.js.erb'}
        format.html { redirect_to myComments.post}
      end
    else
      respond_to do |format|
        format.js {render 'fail.js.erb'}
        format.html {redirect_to :back}
      end
    end
  end

  def show
    @comment = Comment.find(params[:id])
    # @post = Post.all
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :post_id)
    end
end

app/controllers/post_votes_controller.rb
class PostVotesController < ApplicationController
  before_action :authenticate_user!
  # skip_before_filter :verify_authenticity_token
  def create
    # finds post given url with id
    # '/post_votes/:id'
    post = Post.find(params[:id])

    # binding.pry
    new_vote = PostVote.new(:user => current_user, :post => post)
    # same as new_votes = PostVote.new(:user_id => current_user.id, :post_id => post.id)
    if new_vote.save
      numVotes = post.post_votes.length
      # render json: status: 201
      # this is the response that ajax success will get
      render json: numVotes, status: 201
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index #index.html
    #how do I get data from database and put it here??
    # this will store all the posts in an array 
    @posts = Post.all
    @post = Post.new
    # @comments = Comment.all
    # render json: @posts
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      # redirect_to posts_path
      render 'create.json.jbuilder'
    else
      flash[:message] = @post.errors.messages
      # redirect_to :back
      render status: 500
    end
  end

  def show
    # params[:id] will look for the id in the URL
    # this basically retrieves the post with a specific id
    @post = Post.find(params[:id])
    @comments = Comment.where(:post_id => params[:id])
    @comment = Comment.new
  end

  private
    def post_params
      params.require(:post).permit(:title, :url)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def show_current_user
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(:avatar => params[:user][:avatar])
    redirect_to :back
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_votes_helper.rb
module PostVotesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.js.erb
var new_comment = "<%= raw escape_javascript(render :partial => 'posts/comment', :locals => {:comment => @myComment}) %>";
$('#comment_error').text('');
$('#comments_list').prepend(new_comment);
$('#comment_input').val("");

app/views/comments/fail.js.erb
$('#comment_error').text('**input cannot be blank**');

app/views/comments/show.html.erb
  <table class="table">
    <h5>Content: <%= @comment.content %></h5>
  </table>

app/views/layouts/_header.html.erb
<h2>Homepage1</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="kitty">
<head>
  <title>WDI 5 Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <!-- // <script type="text/javascript" src="https://code.jquery.com/ui/1.11.2/jquery-ui.min.js"></script> -->
  
  <%= csrf_meta_tags %>
</head>
<body class="body-background" >
  <section class="container-fluid">
    <nav class="row">
      <div class="col-xs-12 navbar">
        <h1 class="col-xs-8">WDI 5 Reddit</h1>
        <div class="col-xs-4 userlogin">
        <% if current_user %>
              <!-- default :method is :POST for button_to -->
          <%= current_user.email %>
          <%= button_to "Sign out", destroy_user_session_path, :method =>  :delete %>
          <%= link_to "Edit", edit_user_registration_path %>
          <%= link_to "Edit pic", edit_user_path(current_user) %>
        <% else %>
          <!-- default :method is :GET for link_to -->
          <%= link_to "Sign up", new_user_registration_path %>
          <%= link_to "Sign in", new_user_session_path %>
        <% end %>
        </div>
      </div>
    </nav>
  </section>

  <div ng-view>
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_comment.html.erb
<tr>
  <td><%= comment.content %></td>
  <td><%= comment.user.email %></td>
</tr>

app/views/posts/index.html.erb
<div class="container">
  <%= render 'layouts/header' %>


  <h1>Angular</h1>
  <input type="text" placeholder="Please type something" ng-model="name">

  <h3>{{name}}</h3>
----------------------------------------
<h3>Connect Angular Controller Defined in JS to View</h3>

<div ng-controller="PostCtrl">
  <h6>{{ brand }}</h6>
  <h7>{{ total }}</h7>
  <form ng-submit="addPrice()" name="priceForm">
    <!-- You can now refer to @scope.newPrice in your PostCtrl -->
    <input type="text" placeholder="Add a new price" ng-model="newPrice">
  </form>
  <ul ng-repeat="price in prices track by $index">
    <!-- addPrice() will look for a function inside the PostCtrl -->
    <li>{{ price }}</li>
  </ul>
</div>
----------------------------------------
<!--   <h1>Jquery</h1>
  <input type="text" placeholder="Please type something" id="name_input">

  <h3 id="name"></h3>

  <script type="text/javascript">
    $(document).ready(function(){
      $('#name_input').on('keyup',function(){
        $('#name').text($('#name_input').val());
      })
    })
  </script>
 -->----------------------------------------

<div ng-controller="CompanyCtrl">
  <input type="text" placeholder="Search for companies" ng-model="companyName">
  <ul ng-repeat="company in companies | filter:companyName">
    <li>{{ company }}</li>
    <a href="http://www.{{company}}.com">http://www.{{company}}.com</a>
  </ul>
</div>











  <h1>New Posts</h1>

      <!-- POST METHOD for posts -->
      <%= simple_form_for @post, :method => :post do |f| %>
        
        <%= flash[:message] %>

        <%= f.label :title %>
        <%= f.text_field :title %>

        <%= f.label :url %>
        <%= f.text_field :url %>

        <%= f.submit "Submit" %>
      <% end %>

  <h1>Posts</h1>
  <table class="table table-bordered table-condensed">
    <thead>
      <tr class="info">
        <th class="col-xs-1">ID</th>
        <th class="col-xs-2">Email</th>
        <th class="col-xs-2">Title</th>
        <th class="col-xs-3">URL</th>
        <th class="col-xs-2">Time Posted</th>
        <th class="col-xs-1">Votes</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td class="col-xs-1"><%= post.id %></td>
          <td class="col-xs-2"><%= post.user.email %></td>
          <td class="col-xs-2"><%= link_to post do %><%= post.title %><% end %></td>
          <td class="col-xs-3"><%= post.url %></td>
          <td class="col-xs-2"><%= time_ago_in_words(post.created_at) %></td>
          <td class="col-xs-1"><%= post.post_votes.count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% link_to "New Post", new_post_path %>
</div>

app/views/posts/show.html.erb
<div class="container">
  
  
  <table class="table">
    <h5>Title: <%= @post.title %></h5>
    <h5>URL: <%= @post.url %></h5>
    <h5>Owner: <%= @post.user.email %></h5>
    <h5>Datetime: <%= @post.created_at %></h5>
    <h5>Number of votes: <span id="hihi"><%= @post.post_votes.count %></span></h5>
  </table>
  
  <%= button_to("VOTE", "#", :class => "button_vote", 'data-id' => @post.id) %>
  
  <%= form_for @comment, :remote => true, :html => {'data-postId' => @post.id} do |f| %>
    <%= f.label :content %>
    <%= f.text_field :content, :id =>'comment_input' %>
    <%= f.text_field :post_id, :value => @post.id, :hidden => true %>
    <%= f.submit "Submit comment" %>
  <% end %>
  <div id='comment_error'></div>
  <h1>Comments</h1>
  
  <table class="table table-bordered table-condensed">
    
    <thead>
      <tr>
        <th>Content</th>
        <th>Owner</th>
      </tr>
    </thead>
    
    <tbody id='comments_list'>
      <% @post.comments.reverse.each do |comment| %>
        <!-- if you don't need to pass variables in, you can omit :partial => -->
        <%= render :partial => "comment", :locals => {:comment => comment} %>
      <% end %>
    </tbody>

  </table>


</div>

app/views/static_pages/index.html.erb
Hello

app/views/users/_post.html.erb
<tr>
  <td class="col-xs-1"><%= post.id %></td>
  <td class="col-xs-3"><%= link_to post.user do %><%= post.user.email %><% end %></td>
  <td class="col-xs-2"><%= link_to post do %><%= post.title %><% end %></td>
  <td class="col-xs-3"><%= post.url %></td>
  <td class="col-xs-2"><%= time_ago_in_words(post.created_at) %></td>
</tr>

app/views/users/edit.html.erb
<h2> Editz </h2>

<%= image_tag @user.avatar.url %>
<%= image_tag @user.avatar.url(:medium) %>
<%= image_tag @user.avatar.url(:thumb) %>

<%= form_for @user do |f| %>
  <%= f.label "Pick Profile picture" %>
  <%= f.file_field :avatar %>
  <%= f.submit "Upload Profile Picture" %>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <table class="table">
    <h2>Owner: <%= @user.email %></h2>
    <h5>Created: <%= @user.created_at %></h5>
  </table>

  <h1>Posts</h1>
  
  <table class="table table-bordered table-condensed">
    <thead>
      <tr class="info">
        <th class="col-xs-1">ID</th>
        <th class="col-xs-3">Email</th>
        <th class="col-xs-2">Title</th>
        <th class="col-xs-3">URL</th>
        <th class="col-xs-2">Time Posted</th>
      </tr>
    </thead>
    <tbody>
      <% @user.posts.each do |post| %>
        <%= render :partial => 'post', :locals => {:post => post} %>
      <% end %>
    </tbody>
  </table>


  <h1>Comments</h1>

  <table class="table table-bordered table-condensed">
    
    <thead>
      <tr class="success">
        <th>Post</th>
        <th>Content</th>
        <th>Owner</th>
        <th>Time Posted</th>
      </tr>
    </thead>

    <tbody>
      <% @user.comments.each do |comment| %>
        <tr>
          <td><%= comment.post.title %></td>
          <td><%= comment.content %></td>
          <td><%= comment.user.email %></td>
          <td><%= time_ago_in_words(comment.created_at) %></td>
        </tr>
      <% end %>
    </tbody>

  </table>
</div>